// H1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    self setmodel( "body_usmc_desert_assault_james_at4" );
    self attach( "head_usmc_desert_support_james", "", 1 );
    self.headmodel = "head_usmc_desert_support_james";
    self.voice = "american";
    self setclothtype( "vestlight" );
}

precache()
{
    precachemodel( "body_usmc_desert_assault_james_at4" );
    precachemodel( "head_usmc_desert_support_james" );
}
